package com.example.myCat.entities;
// Generated 2018-6-8 0:41:39 by Hibernate Tools 5.2.10.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ESystemUser generated by hbm2java
 */
@Entity
@Table(name = "e_system_user", catalog = "spring_boot")
public class ESystemUser implements java.io.Serializable {

	private Integer id;
	private String username;
	private String password;
	private String lastLogin;
	private Integer groupId;
	private Set<SystemMessage> systemMessages = new HashSet<SystemMessage>(0);

	public ESystemUser() {
	}

	public ESystemUser(String username, String password, String lastLogin, Integer groupId,
			Set<SystemMessage> systemMessages) {
		this.username = username;
		this.password = password;
		this.lastLogin = lastLogin;
		this.groupId = groupId;
		this.systemMessages = systemMessages;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "username")
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	@Column(name = "password")
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "last_login", length = 14)
	public String getLastLogin() {
		return this.lastLogin;
	}

	public void setLastLogin(String lastLogin) {
		this.lastLogin = lastLogin;
	}

	@Column(name = "group_id")
	public Integer getGroupId() {
		return this.groupId;
	}

	public void setGroupId(Integer groupId) {
		this.groupId = groupId;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ESystemUser")
	public Set<SystemMessage> getSystemMessages() {
		return this.systemMessages;
	}

	public void setSystemMessages(Set<SystemMessage> systemMessages) {
		this.systemMessages = systemMessages;
	}

}
