package com.example.myCat.entities;
// Generated 2018-6-8 0:41:39 by Hibernate Tools 5.2.10.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * EUpvote generated by hbm2java
 */
@Entity
@Table(name = "e_upvote", catalog = "spring_boot")
public class EUpvote implements java.io.Serializable {

	private Integer id;
	private EUser EUser;
	private EVblog EVblog;
	private String name;
	private String text;
	private String ip;
	private String befrom;
	private String createDate;

	public EUpvote() {
	}

	public EUpvote(EUser EUser, EVblog EVblog, String name, String text, String ip, String befrom, String createDate) {
		this.EUser = EUser;
		this.EVblog = EVblog;
		this.name = name;
		this.text = text;
		this.ip = ip;
		this.befrom = befrom;
		this.createDate = createDate;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "user_Id")
	public EUser getEUser() {
		return this.EUser;
	}

	public void setEUser(EUser EUser) {
		this.EUser = EUser;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "vBlog_Id")
	public EVblog getEVblog() {
		return this.EVblog;
	}

	public void setEVblog(EVblog EVblog) {
		this.EVblog = EVblog;
	}

	@Column(name = "name")
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "text")
	public String getText() {
		return this.text;
	}

	public void setText(String text) {
		this.text = text;
	}

	@Column(name = "ip", length = 100)
	public String getIp() {
		return this.ip;
	}

	public void setIp(String ip) {
		this.ip = ip;
	}

	@Column(name = "befrom", length = 100)
	public String getBefrom() {
		return this.befrom;
	}

	public void setBefrom(String befrom) {
		this.befrom = befrom;
	}

	@Column(name = "createDate", length = 14)
	public String getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(String createDate) {
		this.createDate = createDate;
	}

}
