package com.example.myCat.entities;
// Generated 2018-6-8 0:41:39 by Hibernate Tools 5.2.10.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * EUserCatRef generated by hbm2java
 */
@Entity
@Table(name = "e_user_cat_ref", catalog = "spring_boot")
public class EUserCatRef implements java.io.Serializable {

	private Integer id;
	private ECat ECat;
	private EUser EUser;

	public EUserCatRef() {
	}

	public EUserCatRef(ECat ECat, EUser EUser) {
		this.ECat = ECat;
		this.EUser = EUser;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "cat_id")
	public ECat getECat() {
		return this.ECat;
	}

	public void setECat(ECat ECat) {
		this.ECat = ECat;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "user_id")
	public EUser getEUser() {
		return this.EUser;
	}

	public void setEUser(EUser EUser) {
		this.EUser = EUser;
	}

}
