package com.example.myCat.entities;
// Generated 2018-6-8 0:41:39 by Hibernate Tools 5.2.10.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.Table;

/**
 * EVblog generated by hbm2java
 */
@Entity
@Table(name = "e_vblog", catalog = "spring_boot")
public class EVblog implements java.io.Serializable {

	private Integer id;
	private EUser EUser;
	private String title;
	private String text;
	private String createDate;
	private Integer categoryId;
	private Integer hits;
	private Integer state;
	private String blogType;
	private ECategory ECategory;
	private Set<EUpvote> EUpvotes = new HashSet<EUpvote>(0);
	private Set<EComment> EComments = new HashSet<EComment>(0);

	public EVblog() {
	}

	public EVblog(EUser EUser, String title, String text, String createDate, Integer categoryId, Integer hits,
			Integer state, String blogType, ECategory ECategory, Set<EUpvote> EUpvotes, Set<EComment> EComments) {
		this.EUser = EUser;
		this.title = title;
		this.text = text;
		this.createDate = createDate;
		this.categoryId = categoryId;
		this.hits = hits;
		this.state = state;
		this.blogType = blogType;
		this.ECategory = ECategory;
		this.EUpvotes = EUpvotes;
		this.EComments = EComments;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "user_Id")
	public EUser getEUser() {
		return this.EUser;
	}

	public void setEUser(EUser EUser) {
		this.EUser = EUser;
	}

	@Column(name = "title")
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@Column(name = "text")
	public String getText() {
		return this.text;
	}

	public void setText(String text) {
		this.text = text;
	}

	@Column(name = "create_date", length = 14)
	public String getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(String createDate) {
		this.createDate = createDate;
	}

	@Column(name = "Category_Id")
	public Integer getCategoryId() {
		return this.categoryId;
	}

	public void setCategoryId(Integer categoryId) {
		this.categoryId = categoryId;
	}

	@Column(name = "hits")
	public Integer getHits() {
		return this.hits;
	}

	public void setHits(Integer hits) {
		this.hits = hits;
	}

	@Column(name = "state")
	public Integer getState() {
		return this.state;
	}

	public void setState(Integer state) {
		this.state = state;
	}

	@Column(name = "blog_type", length = 2)
	public String getBlogType() {
		return this.blogType;
	}

	public void setBlogType(String blogType) {
		this.blogType = blogType;
	}

	@OneToOne(fetch = FetchType.LAZY, mappedBy = "EVblog")
	public ECategory getECategory() {
		return this.ECategory;
	}

	public void setECategory(ECategory ECategory) {
		this.ECategory = ECategory;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "EVblog")
	public Set<EUpvote> getEUpvotes() {
		return this.EUpvotes;
	}

	public void setEUpvotes(Set<EUpvote> EUpvotes) {
		this.EUpvotes = EUpvotes;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "EVblog")
	public Set<EComment> getEComments() {
		return this.EComments;
	}

	public void setEComments(Set<EComment> EComments) {
		this.EComments = EComments;
	}

}
