package com.example.myCat.entities;
// Generated 2018-6-8 0:41:39 by Hibernate Tools 5.2.10.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * SystemMessage generated by hbm2java
 */
@Entity
@Table(name = "system_message", catalog = "spring_boot")
public class SystemMessage implements java.io.Serializable {

	private Integer id;
	private ESystemUser ESystemUser;
	private UserGroup userGroup;
	private String systemTopic;
	private String systemContent;

	public SystemMessage() {
	}

	public SystemMessage(ESystemUser ESystemUser, UserGroup userGroup, String systemTopic, String systemContent) {
		this.ESystemUser = ESystemUser;
		this.userGroup = userGroup;
		this.systemTopic = systemTopic;
		this.systemContent = systemContent;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "send_id")
	public ESystemUser getESystemUser() {
		return this.ESystemUser;
	}

	public void setESystemUser(ESystemUser ESystemUser) {
		this.ESystemUser = ESystemUser;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "group_id")
	public UserGroup getUserGroup() {
		return this.userGroup;
	}

	public void setUserGroup(UserGroup userGroup) {
		this.userGroup = userGroup;
	}

	@Column(name = "system_topic", length = 60)
	public String getSystemTopic() {
		return this.systemTopic;
	}

	public void setSystemTopic(String systemTopic) {
		this.systemTopic = systemTopic;
	}

	@Column(name = "system_content")
	public String getSystemContent() {
		return this.systemContent;
	}

	public void setSystemContent(String systemContent) {
		this.systemContent = systemContent;
	}

}
