package com.example.myCat.entities;
// Generated 2018-6-8 0:41:39 by Hibernate Tools 5.2.10.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * UserGroup generated by hbm2java
 */
@Entity
@Table(name = "user_group", catalog = "spring_boot")
public class UserGroup implements java.io.Serializable {

	private Integer id;
	private UserGroup userGroup;
	private int groupId;
	private String groupName;
	private Integer groupLevel;
	private Set<EUser> EUsers = new HashSet<EUser>(0);
	private Set<UserGroup> userGroups = new HashSet<UserGroup>(0);
	private Set<Menu> menus = new HashSet<Menu>(0);
	private Set<SystemMessage> systemMessages = new HashSet<SystemMessage>(0);

	public UserGroup() {
	}

	public UserGroup(int groupId, String groupName) {
		this.groupId = groupId;
		this.groupName = groupName;
	}

	public UserGroup(UserGroup userGroup, int groupId, String groupName, Integer groupLevel, Set<EUser> EUsers,
			Set<UserGroup> userGroups, Set<Menu> menus, Set<SystemMessage> systemMessages) {
		this.userGroup = userGroup;
		this.groupId = groupId;
		this.groupName = groupName;
		this.groupLevel = groupLevel;
		this.EUsers = EUsers;
		this.userGroups = userGroups;
		this.menus = menus;
		this.systemMessages = systemMessages;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "parent_group_id")
	public UserGroup getUserGroup() {
		return this.userGroup;
	}

	public void setUserGroup(UserGroup userGroup) {
		this.userGroup = userGroup;
	}

	@Column(name = "group_id", nullable = false)
	public int getGroupId() {
		return this.groupId;
	}

	public void setGroupId(int groupId) {
		this.groupId = groupId;
	}

	@Column(name = "group_name", nullable = false, length = 20)
	public String getGroupName() {
		return this.groupName;
	}

	public void setGroupName(String groupName) {
		this.groupName = groupName;
	}

	@Column(name = "group_level")
	public Integer getGroupLevel() {
		return this.groupLevel;
	}

	public void setGroupLevel(Integer groupLevel) {
		this.groupLevel = groupLevel;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "userGroup")
	public Set<EUser> getEUsers() {
		return this.EUsers;
	}

	public void setEUsers(Set<EUser> EUsers) {
		this.EUsers = EUsers;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "userGroup")
	public Set<UserGroup> getUserGroups() {
		return this.userGroups;
	}

	public void setUserGroups(Set<UserGroup> userGroups) {
		this.userGroups = userGroups;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "userGroup")
	public Set<Menu> getMenus() {
		return this.menus;
	}

	public void setMenus(Set<Menu> menus) {
		this.menus = menus;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "userGroup")
	public Set<SystemMessage> getSystemMessages() {
		return this.systemMessages;
	}

	public void setSystemMessages(Set<SystemMessage> systemMessages) {
		this.systemMessages = systemMessages;
	}

}
