package com.example.myCat.entities;
// Generated 2018-6-8 0:41:39 by Hibernate Tools 5.2.10.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * UserAttention generated by hbm2java
 */
@Entity
@Table(name = "user_attention", catalog = "spring_boot")
public class UserAttention implements java.io.Serializable {

	private Integer id;
	private EUser EUserByAttentionId;
	private EUser EUserByUserId;
	private String attentionDate;

	public UserAttention() {
	}

	public UserAttention(EUser EUserByAttentionId, EUser EUserByUserId) {
		this.EUserByAttentionId = EUserByAttentionId;
		this.EUserByUserId = EUserByUserId;
	}

	public UserAttention(EUser EUserByAttentionId, EUser EUserByUserId, String attentionDate) {
		this.EUserByAttentionId = EUserByAttentionId;
		this.EUserByUserId = EUserByUserId;
		this.attentionDate = attentionDate;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "attention_id", nullable = false)
	public EUser getEUserByAttentionId() {
		return this.EUserByAttentionId;
	}

	public void setEUserByAttentionId(EUser EUserByAttentionId) {
		this.EUserByAttentionId = EUserByAttentionId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "user_id", nullable = false)
	public EUser getEUserByUserId() {
		return this.EUserByUserId;
	}

	public void setEUserByUserId(EUser EUserByUserId) {
		this.EUserByUserId = EUserByUserId;
	}

	@Column(name = "attention_date", length = 14)
	public String getAttentionDate() {
		return this.attentionDate;
	}

	public void setAttentionDate(String attentionDate) {
		this.attentionDate = attentionDate;
	}

}
